<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SelfTech-027" failures="1" tests="2" name="Error Validations Test" time="0.131" errors="0" timestamp="2023-01-20T18:54:28 IST">
  <testcase classname="RahulShetty.SeleniumFrameworkShopping.ErrorValidations" name="LoginErrorValidation" time="0.008">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="RahulShetty.SeleniumFrameworkShopping.ErrorValidations" name="LoginErrorValidation" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at RahulShetty.SeleniumFrameworkShopping.ErrorValidations.LoginErrorValidation(ErrorValidations.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="RahulShetty.SeleniumFrameworkShopping.ErrorValidations" name="ProductErrorVaidation" time="0.0">
    <ignored/>
  </testcase> <!-- ProductErrorVaidation -->
</testsuite> <!-- Error Validations Test -->
